### ISSUE TITLE
Panic when listing notifiers

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#451]
```
scalingo -a <appname> notifiers
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Scalingo/cli/notifiers.eventTypesToString(0xc000133000, 0x23, 0x2a, 0x1095bb0, 0x0, 0x0, 0x0, 0x0)
    /home/emichon/Documents/Scalingo/golang/src/github.com/Scalingo/cli/notifiers/list.go:57 +0x2cc
github.com/Scalingo/cli/notifiers.List(0x7ffe6ded0761, 0x2, 0x2, 0x6)
    /home/emichon/Documents/Scalingo/golang/src/github.com/Scalingo/cli/notifiers/list.go:36 +0x2fc
github.com/Scalingo/cli/cmd.glob..func103(0xc0000ef1e0)
```

**Comment by EtienneM** [comment]
Which app is impacted?

**Comment by Soulou** [comment]
`db`
